name: Release
on:
  push:
    tags:
      - v**

- name: Chart | Push
  uses: appany/helm-oci-chart-releaser@v0.3.0
  with:
    name: raas
    repository: tylerauerbeck
    tag: ${{  github.ref_name }}
    path: .
    registry: ghcr.io
    registry_username: ${{ secrets.REGISTRY_USERNAME }}
    registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    update_dependencies: 'true'