apiVersion: v1
kind: Service
metadata:
  name: {{ include "raas.fullname" . }}
  labels:
    {{- include "raas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: raas-echo
