name: Release
on:
  push:
    tags:
      - v**

jobs:
  publish-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.1
        with:
          name: raas
          repository: tylerauerbeck
          tag: ${{  github.ref_name }}
          path: .
          registry: ghcr.io
          registry_username: ${{github.actor}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
